name: 自动采集

# 触发条件
on:
  # push的时候触发
  # push:
  #   branches: main
  workflow_dispatch:
  # 定时触发
  schedule:
    - cron:  '1 6,18 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.7'
    - name: 加载缓存  
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r requirements.txt
    - name: 执行任务
      run: |
        python main2.py
          
    - name: 提交更改
      run: |                 
         git config --local user.email "xhrzg2017@gmail.com"
         git config --local user.name "xhrzg2017"
         git add subscribe/clash.yaml
         git commit -m "更新订阅链接"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.token }}
        branch: main
